### ISSUE TITLE
Is it still actual

### ISSUE THREAD

**Issue by vbezruchkin** [akalongman/php-geopayment#1]
Hi,

Going to implement this package as a module for an open source CMS. I wonder if the code is still actual and if you still use it in production.

Thanks in advance.

**Comment by akalongman** [comment]
@vbezruchkin yes, I use this package in the production. But feel free to improve the package :)

**Comment by vbezruchkin** [comment]
Ok, I will try to do that :) Any plans for Liberty bank?
Thanks @akalongman

**Comment by akalongman** [comment]
@vbezruchkin it's pretty easy to add new bank payment in this package. If you have a documentation for liberty bank, send me and I will add

**Comment by vbezruchkin** [comment]
I will ask for it from a friend of mine in Tbilisi :)  Not sure if he has it though. Love your city, BTW! Thanks in advance.

**Comment by akalongman** [comment]
Thank you, our city is a really amazing :)
