### ISSUE TITLE
Pass fixed amount & default data

### ISSUE THREAD

**Issue by vbezruchkin** [akalongman/php-geopayment#4]
Sorry to bother you again. I don't have enough docs to move on with this myself :( 

Going to use it for BoG integration. Anyhow, I don't know how to pass a fixed amount to the server. Here is what we have now:

![image](https://cloud.githubusercontent.com/assets/2760455/26346074/df6e8330-3fc6-11e7-9b21-6b9a63d75d16.png)

I see I can pass my internal params, but that's not the case.

Thanks in advance.

**Comment by akalongman** [comment]
Could you show full documentation from BOG?

**Comment by vbezruchkin** [comment]
that's the case, man :) I don't have it at the moment.

I thought there was some sort of abstract param that was used across your wrapper class that could be used to pass the amount. Many providers might need a fixed amount to pass, so I believed yours had one.

**Comment by akalongman** [comment]
Ok, you want to pass the parameter in 1 step? Here https://github.com/akalongman/php-geopayment#bog-step-1-redirecting-on-payment-page

**Comment by vbezruchkin** [comment]
No, here is what I try to do. 

1 step when a bill is sent to BoG.

```
require __DIR__ . '/vendor/autoload.php';

$returnURL = IA_RETURN_URL . 'completed/';
$cancelURL = IA_RETURN_URL . 'canceled/';

use Longman\GeoPayment\Payment;

$options = [
    'config_path' => __DIR__ . '/.bog',
];

// Create payment instance
$payment = new Payment('bog', Payment::TYPE_CARD, $options);

// Set mode 'redirect'
$payment->setMode('redirect');

// Set success url
$payment->setSuccessUrl($returnURL);

// Set fail url
$payment->setFailUrl($cancelURL);

// Set order id or any payment identificator in your db
$payment->addParam('order_id', $transaction['sec_key']);

// And simple redirect
$payment->redirect();
```

Then I validate in my check file, send XML response sendErrorResponse() or sendSuccessResponse(). The payment is not registered. This is what I have in the payment check file:

```
require __DIR__ . '/includes/vendor/autoload.php';

use Longman\GeoPayment\Payment;
use Longman\GeoPayment\Logger;

// Create payment instance
$payment = new Payment('bog', Payment::TYPE_CARD, ['config_path' => IA_PLUGINS . 'geopayment/includes/.bog']);

// Create logger
$logger = new Logger();

// Transaction class
$iaTransaction = $iaCore->factory('transaction');

// Set mode 'check'
$payment->setMode('check');

// Here you must check order_id or any other parameters which before redirecting set via $payment->addParam
$order_id = $payment->getParam('o.order_id');
empty($order_id) && $order_id = $_GET['id_order_id']; // using this for test purpose
if (!$order_id) {
	$payment->sendErrorResponse('Order is empty!');
}

// check if order exists
$transaction = $iaTransaction->getBy('sec_key', $order_id);

// file_put_contents(__DIR__ . '/debug.txt', serialize($transaction));

if (empty($transaction)) {
	$payment->sendErrorResponse(iaLanguage::get('no_transaction'));
}

// Build parameters for response
$params = [];
$params['amount'] = $transaction['amount'];
$params['short_desc'] = 'Purchase at XXX';
$params['long_desc'] = $transaction['operation'];

$payment->sendSuccessResponse($params);
```

Please advise how to use your logger as it does not seem to work correctly every time :((

**Comment by vbezruchkin** [comment]
Ignore please. Implemented.
